import React from 'react';

export default function HomePage(props:any){
    return (
        <>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
            <p>HOME</p>
        </>
    );
}